/**
 * OCAT Issue Categories (30 Core + Extensible)
 * Each category has 35-45 questions based on real player complaints
 * Sources: AskGamblers, CasinoGuru, AGCO Standards, Industry Reports
 */

export interface IssueQuestion {
  id: string;
  text: string;
}

export interface IssueCategory {
  id: string;
  name: string;
  description: string;
  riskWeight: number;
  questions: IssueQuestion[];
}

export const ISSUE_CATEGORIES: IssueCategory[] = [
  // PAYMENT & WITHDRAWAL ISSUES (1-5)
  {
    id: "withdrawal_delays",
    name: "Withdrawal Delays",
    description: "Funds stuck in pending status for extended periods",
    riskWeight: 9,
    questions: [
      { id: "wd1", text: "Was your withdrawal request submitted and not processed within 5 business days?" },
      { id: "wd2", text: "Did the casino provide no timeline or estimated completion date?" },
      { id: "wd3", text: "Were you told to wait without any status updates for weeks?" },
      { id: "wd4", text: "Did support claim the withdrawal was 'processing' but never completed?" },
      { id: "wd5", text: "Were you asked to make additional deposits to 'speed up' the withdrawal?" },
      { id: "wd6", text: "Did the casino reverse or cancel your withdrawal without explanation?" },
      { id: "wd7", text: "Were you required to complete additional verification after already being verified?" },
      { id: "wd8", text: "Did the casino claim the withdrawal was 'lost' in their system?" },
      { id: "wd9", text: "Were you told different reasons for the delay by different support agents?" },
      { id: "wd10", text: "Did the casino offer no compensation for the delay?" },
      { id: "wd11", text: "Was the delay longer than 30 days?" },
      { id: "wd12", text: "Did you attempt to contact support multiple times without resolution?" },
      { id: "wd13", text: "Were you unable to contact support about your withdrawal?" },
      { id: "wd14", text: "Did the casino claim a 'system error' caused the delay?" },
      { id: "wd15", text: "Were you asked to withdraw via a different payment method?" },
      { id: "wd16", text: "Did the casino charge fees for the delayed withdrawal?" },
      { id: "wd17", text: "Was your account restricted during the withdrawal delay?" },
      { id: "wd18", text: "Did the casino claim the delay was due to 'payment processor issues'?" },
      { id: "wd19", text: "Were you unable to cancel the withdrawal request?" },
      { id: "wd20", text: "Did the casino ask for proof of funds before releasing the withdrawal?" },
      { id: "wd21", text: "Was the withdrawal eventually processed but with less than expected?" },
      { id: "wd22", text: "Did the casino deduct unexplained fees from the withdrawal?" },
      { id: "wd23", text: "Were you told the delay was due to 'high volume'?" },
      { id: "wd24", text: "Did the casino offer a bonus instead of processing the withdrawal?" },
      { id: "wd25", text: "Was the withdrawal amount changed without your consent?" },
      { id: "wd26", text: "Did support provide generic copy-paste responses about the delay?" },
      { id: "wd27", text: "Were you unable to escalate the issue to a supervisor?" },
      { id: "wd28", text: "Did the casino claim they never received the withdrawal request?" },
      { id: "wd29", text: "Was the delay coinciding with a winning streak?" },
      { id: "wd30", text: "Did the casino require you to play through your balance again?" },
      { id: "wd31", text: "Were you asked to provide bank statements or proof of account ownership?" },
      { id: "wd32", text: "Did the casino claim the withdrawal violated their terms?" },
      { id: "wd33", text: "Was the delay longer than any other player's withdrawal you know of?" },
      { id: "wd34", text: "Did the casino offer no explanation for the delay?" },
      { id: "wd35", text: "Were you told to contact your bank instead of the casino?" },
      { id: "wd36", text: "Did the casino claim the withdrawal was 'pending bank approval'?" },
      { id: "wd37", text: "Was the withdrawal eventually rejected or returned?" },
      { id: "wd38", text: "Did you lose money due to currency fluctuations during the delay?" },
      { id: "wd39", text: "Were you unable to file a complaint with the casino?" },
      { id: "wd40", text: "Did the casino threaten to close your account if you complained?" },
    ],
  },

  {
    id: "withdrawal_denied",
    name: "Withdrawal Denied/Rejected",
    description: "Casino refused to process withdrawal or rejected it without valid reason",
    riskWeight: 10,
    questions: [
      { id: "wdn1", text: "Did the casino deny your withdrawal request without clear explanation?" },
      { id: "wdn2", text: "Were you told the withdrawal violated 'terms and conditions'?" },
      { id: "wdn3", text: "Did the casino claim you had 'suspicious activity' on your account?" },
      { id: "wdn4", text: "Were you accused of bonus abuse or terms violation?" },
      { id: "wdn5", text: "Did the casino confiscate your winnings without explanation?" },
      { id: "wdn6", text: "Was your account closed and funds frozen?" },
      { id: "wdn7", text: "Did the casino claim you were using a VPN or proxy?" },
      { id: "wdn8", text: "Were you told you violated geolocation restrictions?" },
      { id: "wdn9", text: "Did the casino claim you had multiple accounts?" },
      { id: "wdn10", text: "Were you accused of using automated betting tools?" },
      { id: "wdn11", text: "Did the casino claim the withdrawal was 'flagged for review'?" },
      { id: "wdn12", text: "Were you unable to appeal the withdrawal denial?" },
      { id: "wdn13", text: "Did the casino offer no way to dispute the decision?" },
      { id: "wdn14", text: "Was the denial decision made by an automated system?" },
      { id: "wdn15", text: "Did support refuse to explain the reason for denial?" },
      { id: "wdn16", text: "Were you given conflicting reasons for the denial?" },
      { id: "wdn17", text: "Did the casino claim the denial was 'permanent'?" },
      { id: "wdn18", text: "Were your funds forfeited after the denial?" },
      { id: "wdn19", text: "Did the casino offer to keep your funds as a bonus instead?" },
      { id: "wdn20", text: "Was the denial decision made immediately after you requested withdrawal?" },
      { id: "wdn21", text: "Did the casino claim regulatory reasons for the denial?" },
      { id: "wdn22", text: "Were you unable to contact support about the denial?" },
      { id: "wdn23", text: "Did the casino claim the denial was due to 'payment processor restrictions'?" },
      { id: "wdn24", text: "Was the denial decision inconsistent with casino's own terms?" },
      { id: "wdn25", text: "Did the casino claim you were on a 'restricted list'?" },
      { id: "wdn26", text: "Were you unable to verify your identity to appeal?" },
      { id: "wdn27", text: "Did the casino claim the denial was for 'fraud prevention'?" },
      { id: "wdn28", text: "Was the denial decision made by someone who never reviewed your account?" },
      { id: "wdn29", text: "Did the casino offer no compensation for the wrongful denial?" },
      { id: "wdn30", text: "Were you told the denial was 'final' without recourse?" },
      { id: "wdn31", text: "Did the casino keep your funds indefinitely?" },
      { id: "wdn32", text: "Was the denial decision made without notifying you first?" },
      { id: "wdn33", text: "Did the casino refuse to provide documentation of the denial?" },
      { id: "wdn34", text: "Were you unable to request a manual review?" },
      { id: "wdn35", text: "Did the casino claim the denial was due to 'account restrictions'?" },
      { id: "wdn36", text: "Was the denial decision inconsistent with other players' experiences?" },
      { id: "wdn37", text: "Did the casino offer a settlement lower than your actual balance?" },
      { id: "wdn38", text: "Were you told the denial was 'irreversible'?" },
      { id: "wdn39", text: "Did the casino claim the denial was due to 'system limitations'?" },
      { id: "wdn40", text: "Was the denial decision made based on incomplete information?" },
    ],
  },

  {
    id: "deposit_not_credited",
    name: "Deposit Not Credited",
    description: "Money deducted from bank account but not appearing in casino balance",
    riskWeight: 9,
    questions: [
      { id: "dnc1", text: "Did you deposit funds but they never appeared in your casino account?" },
      { id: "dnc2", text: "Was the money deducted from your bank account?" },
      { id: "dnc3", text: "Did the casino claim they never received the deposit?" },
      { id: "dnc4", text: "Were you unable to provide proof of the transaction?" },
      { id: "dnc5", text: "Did the casino refuse to investigate the missing deposit?" },
      { id: "dnc6", text: "Were you asked to deposit again to 'verify' your account?" },
      { id: "dnc7", text: "Did support claim the deposit was 'pending'?" },
      { id: "dnc8", text: "Was the deposit stuck in pending status for more than 24 hours?" },
      { id: "dnc9", text: "Did the casino offer no timeline for crediting the deposit?" },
      { id: "dnc10", text: "Were you told to contact your bank instead of the casino?" },
      { id: "dnc11", text: "Did your bank confirm the transaction was completed?" },
      { id: "dnc12", text: "Did the casino claim the deposit was sent to the 'wrong account'?" },
      { id: "dnc13", text: "Were you asked for additional verification after the deposit?" },
      { id: "dnc14", text: "Did support provide different explanations for the missing deposit?" },
      { id: "dnc15", text: "Was the deposit eventually credited but with a delay?" },
      { id: "dnc16", text: "Did the casino deduct fees from the credited deposit?" },
      { id: "dnc17", text: "Were you unable to contact support about the missing deposit?" },
      { id: "dnc18", text: "Did the casino claim a 'system error' caused the issue?" },
      { id: "dnc19", text: "Were you unable to cancel the deposit request?" },
      { id: "dnc20", text: "Did the casino offer no compensation for the inconvenience?" },
      { id: "dnc21", text: "Was the deposit amount changed without your consent?" },
      { id: "dnc22", text: "Did you have to wait more than 7 days for the deposit to be credited?" },
      { id: "dnc23", text: "Did the casino claim the deposit was 'rejected' by the payment processor?" },
      { id: "dnc24", text: "Were you unable to request a refund for the missing deposit?" },
      { id: "dnc25", text: "Did the casino claim they had no record of the transaction?" },
      { id: "dnc26", text: "Were you asked to provide bank statements as proof?" },
      { id: "dnc27", text: "Did the casino refuse to escalate the issue?" },
      { id: "dnc28", text: "Was the deposit eventually returned to your bank?" },
      { id: "dnc29", text: "Did you incur bank fees due to the failed deposit?" },
      { id: "dnc30", text: "Did the casino claim the deposit was 'flagged for review'?" },
      { id: "dnc31", text: "Were you unable to use the casino while the deposit was pending?" },
      { id: "dnc32", text: "Did the casino offer a bonus instead of crediting the deposit?" },
      { id: "dnc33", text: "Was the deposit eventually credited to a different account?" },
      { id: "dnc34", text: "Did the casino claim the issue was 'beyond their control'?" },
      { id: "dnc35", text: "Were you told to contact the payment processor directly?" },
      { id: "dnc36", text: "Did the casino provide no way to track the deposit status?" },
      { id: "dnc37", text: "Was the deposit lost due to a currency conversion issue?" },
      { id: "dnc38", text: "Did you lose money due to exchange rate changes during the delay?" },
      { id: "dnc39", text: "Did the casino refuse to provide a transaction ID?" },
      { id: "dnc40", text: "Were you unable to file a complaint about the missing deposit?" },
    ],
  },

  {
    id: "payment_method_rejected",
    name: "Payment Method Rejected",
    description: "Withdrawal rejected due to payment method issues or forced to use expensive method",
    riskWeight: 7,
    questions: [
      { id: "pmr1", text: "Was your preferred withdrawal method suddenly rejected?" },
      { id: "pmr2", text: "Did the casino offer no alternative payment methods?" },
      { id: "pmr3", text: "Were you forced to use an expensive or inconvenient payment method?" },
      { id: "pmr4", text: "Did the casino charge excessive fees for the alternative method?" },
      { id: "pmr5", text: "Was the payment method that worked for deposits rejected for withdrawals?" },
      { id: "pmr6", text: "Did the casino claim the payment method was 'no longer available'?" },
      { id: "pmr7", text: "Were you unable to withdraw to your original deposit method?" },
      { id: "pmr8", text: "Did the casino require cryptocurrency withdrawal with high fees?" },
      { id: "pmr9", text: "Were you charged currency conversion fees not disclosed upfront?" },
      { id: "pmr10", text: "Did the casino reject your bank transfer without explanation?" },
      { id: "pmr11", text: "Were you unable to use e-wallets for withdrawal?" },
      { id: "pmr12", text: "Did the casino claim payment method restrictions were 'regulatory'?" },
      { id: "pmr13", text: "Were you offered only wire transfer at high cost?" },
      { id: "pmr14", text: "Did the casino reject your debit card withdrawal?" },
      { id: "pmr15", text: "Were you unable to use the same payment method twice?" },
      { id: "pmr16", text: "Did the casino require you to verify the payment method again?" },
      { id: "pmr17", text: "Were you charged fees for payment method verification?" },
      { id: "pmr18", text: "Did the casino offer no refund for rejected payment attempts?" },
      { id: "pmr19", text: "Were you unable to request a different payment method?" },
      { id: "pmr20", text: "Did the casino claim the payment method was 'flagged' for fraud?" },
      { id: "pmr21", text: "Were you told the payment method was 'temporarily unavailable'?" },
      { id: "pmr22", text: "Did the casino require you to use a third-party payment service?" },
      { id: "pmr23", text: "Were you charged intermediary fees not disclosed?" },
      { id: "pmr24", text: "Did the casino reject your prepaid card?" },
      { id: "pmr25", text: "Were you unable to use mobile payment methods?" },
      { id: "pmr26", text: "Did the casino offer no explanation for payment method rejection?" },
      { id: "pmr27", text: "Were you asked to provide additional documentation for the payment method?" },
      { id: "pmr28", text: "Did the casino claim the payment method required 'special approval'?" },
      { id: "pmr29", text: "Were you unable to escalate the payment method issue?" },
      { id: "pmr30", text: "Did support provide conflicting information about payment methods?" },
      { id: "pmr31", text: "Were you charged fees for each payment method attempt?" },
      { id: "pmr32", text: "Did the casino offer cryptocurrency as the only withdrawal option?" },
      { id: "pmr33", text: "Were you unable to use your country's preferred payment method?" },
      { id: "pmr34", text: "Did the casino claim payment method restrictions were 'permanent'?" },
      { id: "pmr35", text: "Were you offered a settlement to a different payment method?" },
    ],
  },

  {
    id: "account_verification_delays",
    name: "Account Verification Delays",
    description: "KYC verification stuck in review for extended periods",
    riskWeight: 8,
    questions: [
      { id: "avd1", text: "Has your account been stuck in verification for more than 7 days?" },
      { id: "avd2", text: "Did the casino provide no timeline for verification completion?" },
      { id: "avd3", text: "Were you unable to withdraw funds while verification was pending?" },
      { id: "avd4", text: "Did support claim verification was 'in progress' indefinitely?" },
      { id: "avd5", text: "Were you asked to resubmit documents multiple times?" },
      { id: "avd6", text: "Did the casino claim documents were 'unclear' without specifics?" },
      { id: "avd7", text: "Were you unable to contact support about verification status?" },
      { id: "avd8", text: "Did support provide different timelines for verification?" },
      { id: "avd9", text: "Was verification delayed longer than 30 days?" },
      { id: "avd10", text: "Did the casino claim a 'system error' caused the delay?" },
      { id: "avd11", text: "Were you unable to cancel the verification process?" },
      { id: "avd12", text: "Did the casino offer no compensation for the delay?" },
      { id: "avd13", text: "Were you asked for documents beyond standard KYC requirements?" },
      { id: "avd14", text: "Did the casino claim verification was 'pending manual review'?" },
      { id: "avd15", text: "Were you unable to escalate the verification issue?" },
      { id: "avd16", text: "Did support provide generic copy-paste responses about verification?" },
      { id: "avd17", text: "Was verification delayed coinciding with a winning streak?" },
      { id: "avd18", text: "Did the casino claim verification was 'pending third-party review'?" },
      { id: "avd19", text: "Were you unable to request a manual review?" },
      { id: "avd20", text: "Did the casino refuse to provide verification status updates?" },
      { id: "avd21", text: "Was your account restricted while verification was pending?" },
      { id: "avd22", text: "Did the casino claim verification was 'under investigation'?" },
      { id: "avd23", text: "Were you unable to use the casino while verification was pending?" },
      { id: "avd24", text: "Did the casino offer a bonus instead of completing verification?" },
      { id: "avd25", text: "Was verification eventually rejected after a long delay?" },
      { id: "avd26", text: "Did the casino claim verification was 'lost' in their system?" },
      { id: "avd27", text: "Were you asked to verify your identity multiple times?" },
      { id: "avd28", text: "Did support claim they never received your documents?" },
      { id: "avd29", text: "Were you unable to provide additional information to speed up verification?" },
      { id: "avd30", text: "Did the casino claim verification was 'pending compliance review'?" },
      { id: "avd31", text: "Was verification delayed due to 'high volume'?" },
      { id: "avd32", text: "Did the casino refuse to provide a verification reference number?" },
      { id: "avd33", text: "Were you told verification was 'not required' initially, then required later?" },
      { id: "avd34", text: "Did the casino claim verification was 'pending bank confirmation'?" },
      { id: "avd35", text: "Were you unable to file a complaint about the verification delay?" },
    ],
  },

  // ACCOUNT MANAGEMENT ISSUES (6-10)
  {
    id: "account_locked",
    name: "Account Locked/Blocked",
    description: "Account suddenly frozen without explanation or warning",
    riskWeight: 10,
    questions: [
      { id: "al1", text: "Was your account suddenly locked without warning?" },
      { id: "al2", text: "Did the casino provide no explanation for the lock?" },
      { id: "al3", text: "Were you unable to access your account balance?" },
      { id: "al4", text: "Did the casino claim 'suspicious activity' without details?" },
      { id: "al5", text: "Were your funds frozen in the locked account?" },
      { id: "al6", text: "Did the casino refuse to unlock your account?" },
      { id: "al7", text: "Were you unable to contact support about the lock?" },
      { id: "al8", text: "Did support claim the lock was 'permanent'?" },
      { id: "al9", text: "Were you unable to appeal the account lock?" },
      { id: "al10", text: "Did the casino lock your account coinciding with a withdrawal request?" },
      { id: "al11", text: "Were you locked out immediately after a big win?" },
      { id: "al12", text: "Did the casino claim you violated 'terms and conditions'?" },
      { id: "al13", text: "Were you unable to provide information to unlock the account?" },
      { id: "al14", text: "Did support provide different reasons for the lock?" },
      { id: "al15", text: "Was the lock decision made by an automated system?" },
      { id: "al16", text: "Did the casino offer no way to dispute the lock?" },
      { id: "al17", text: "Were you unable to request a manual review?" },
      { id: "al18", text: "Did the casino claim the lock was due to 'fraud prevention'?" },
      { id: "al19", text: "Were you told the lock was 'irreversible'?" },
      { id: "al20", text: "Did the casino offer no compensation for the lock?" },
      { id: "al21", text: "Was the lock decision made without reviewing your account?" },
      { id: "al22", text: "Did the casino claim you were using a VPN or proxy?" },
      { id: "al23", text: "Were you locked out due to logging in from a different location?" },
      { id: "al24", text: "Did the casino claim you violated geolocation restrictions?" },
      { id: "al25", text: "Were you unable to contact support via multiple channels?" },
      { id: "al26", text: "Did support refuse to explain the lock reason?" },
      { id: "al27", text: "Was the lock decision made based on incomplete information?" },
      { id: "al28", text: "Did the casino claim you had 'multiple accounts'?" },
      { id: "al29", text: "Were you unable to retrieve your account data?" },
      { id: "al30", text: "Did the casino refuse to provide documentation of the lock?" },
      { id: "al31", text: "Was the lock decision inconsistent with casino's own terms?" },
      { id: "al32", text: "Did the casino threaten legal action if you complained?" },
      { id: "al33", text: "Were you unable to file a complaint about the lock?" },
      { id: "al34", text: "Did the casino claim the lock was 'beyond their control'?" },
      { id: "al35", text: "Were you told the lock was due to 'account restrictions'?" },
    ],
  },

  {
    id: "bonus_forfeited",
    name: "Bonus/Winnings Forfeited",
    description: "Bonus or winnings removed without valid reason",
    riskWeight: 8,
    questions: [
      { id: "bf1", text: "Did the casino remove your bonus without explanation?" },
      { id: "bf2", text: "Were your winnings forfeited without clear reason?" },
      { id: "bf3", text: "Did the casino claim you violated bonus terms?" },
      { id: "bf4", text: "Were you unable to understand the bonus terms?" },
      { id: "bf5", text: "Did the casino claim you used 'prohibited betting patterns'?" },
      { id: "bf6", text: "Were you accused of 'bonus abuse' without evidence?" },
      { id: "bf7", text: "Did the casino remove bonus after you met wagering requirements?" },
      { id: "bf8", text: "Were your winnings reset to zero without explanation?" },
      { id: "bf9", text: "Did the casino claim the bonus was 'no longer valid'?" },
      { id: "bf10", text: "Were you unable to appeal the forfeiture?" },
      { id: "bf11", text: "Did support provide conflicting reasons for forfeiture?" },
      { id: "bf12", text: "Was the forfeiture decision made by an automated system?" },
      { id: "bf13", text: "Did the casino offer no way to dispute the decision?" },
      { id: "bf14", text: "Were you unable to request a manual review?" },
      { id: "bf15", text: "Did the casino claim the forfeiture was 'permanent'?" },
      { id: "bf16", text: "Were you offered no compensation for the forfeiture?" },
      { id: "bf17", text: "Was the forfeiture decision made without reviewing your account?" },
      { id: "bf18", text: "Did the casino change bonus terms after you accepted them?" },
      { id: "bf19", text: "Were you unable to contact support about the forfeiture?" },
      { id: "bf20", text: "Did the casino claim the forfeiture was due to 'system error'?" },
      { id: "bf21", text: "Were you told the forfeiture was 'irreversible'?" },
      { id: "bf22", text: "Did the casino claim you violated 'responsible gambling' rules?" },
      { id: "bf23", text: "Were you unable to provide information to appeal?" },
      { id: "bf24", text: "Did the casino offer a lower settlement than your winnings?" },
      { id: "bf25", text: "Was the forfeiture coinciding with a winning streak?" },
      { id: "bf26", text: "Did the casino claim the bonus was 'only for new players'?" },
      { id: "bf27", text: "Were you unable to escalate the forfeiture issue?" },
      { id: "bf28", text: "Did support refuse to explain the forfeiture reason?" },
      { id: "bf29", text: "Was the forfeiture decision made based on incomplete information?" },
      { id: "bf30", text: "Did the casino claim the forfeiture was 'beyond their control'?" },
      { id: "bf31", text: "Were you unable to file a complaint about the forfeiture?" },
      { id: "bf32", text: "Did the casino threaten to close your account if you complained?" },
      { id: "bf33", text: "Was the forfeiture decision inconsistent with other players?" },
      { id: "bf34", text: "Did the casino claim the bonus had 'expired'?" },
      { id: "bf35", text: "Were you offered a bonus instead of your winnings?" },
    ],
  },

  {
    id: "game_rigged",
    name: "Game Rigged/Unfair",
    description: "Suspicion that games are manipulated against the player",
    riskWeight: 9,
    questions: [
      { id: "gr1", text: "Do you suspect the games are rigged against you?" },
      { id: "gr2", text: "Have you experienced unusual losing patterns?" },
      { id: "gr3", text: "Did the casino refuse to provide RNG certification?" },
      { id: "gr4", text: "Were odds not disclosed for the games you played?" },
      { id: "gr5", text: "Did the casino claim games were 'certified' without proof?" },
      { id: "gr6", text: "Have you noticed consistent losses despite good strategy?" },
      { id: "gr7", text: "Did the casino change game odds without notice?" },
      { id: "gr8", text: "Were you unable to verify game fairness?" },
      { id: "gr9", text: "Did the casino refuse to provide payout percentages?" },
      { id: "gr10", text: "Have you experienced more losses than statistically probable?" },
      { id: "gr11", text: "Did the casino claim games were 'independently tested'?" },
      { id: "gr12", text: "Were you unable to find RNG certification information?" },
      { id: "gr13", text: "Did the casino offer no way to verify game fairness?" },
      { id: "gr14", text: "Have you noticed patterns suggesting predetermined outcomes?" },
      { id: "gr15", text: "Did the casino refuse to provide audit reports?" },
      { id: "gr16", text: "Were you unable to access game history or statistics?" },
      { id: "gr17", text: "Did the casino claim games were 'audited' without details?" },
      { id: "gr18", text: "Have you experienced unusual streaks of losses?" },
      { id: "gr19", text: "Did the casino refuse to explain game mechanics?" },
      { id: "gr20", text: "Were odds different than advertised?" },
      { id: "gr21", text: "Did the casino change game rules after you started playing?" },
      { id: "gr22", text: "Have you noticed differences in game performance?" },
      { id: "gr23", text: "Did the casino refuse to provide Return to Player (RTP) information?" },
      { id: "gr24", text: "Were you unable to find independent game testing information?" },
      { id: "gr25", text: "Did the casino claim game fairness was 'proprietary'?" },
      { id: "gr26", text: "Have you experienced losses immediately after deposits?" },
      { id: "gr27", text: "Did the casino refuse to explain loss patterns?" },
      { id: "gr28", text: "Were you unable to contact support about game fairness?" },
      { id: "gr29", text: "Did the casino offer no compensation for suspected rigging?" },
      { id: "gr30", text: "Have you compared your results to other players?" },
      { id: "gr31", text: "Did the casino claim game fairness concerns were 'invalid'?" },
      { id: "gr32", text: "Were you unable to file a complaint about game fairness?" },
      { id: "gr33", text: "Did the casino threaten to close your account if you complained?" },
      { id: "gr34", text: "Have you documented unusual game behavior?" },
      { id: "gr35", text: "Did the casino refuse to investigate your concerns?" },
    ],
  },

  {
    id: "support_unresponsive",
    name: "Support Unresponsive",
    description: "Customer support doesn't respond or provides unhelpful answers",
    riskWeight: 7,
    questions: [
      { id: "su1", text: "Did support fail to respond to your inquiries?" },
      { id: "su2", text: "Were you unable to reach support via any channel?" },
      { id: "su3", text: "Did support take more than 48 hours to respond?" },
      { id: "su4", text: "Were support responses unhelpful or irrelevant?" },
      { id: "su5", text: "Did support provide generic copy-paste answers?" },
      { id: "su6", text: "Were you unable to escalate issues to a supervisor?" },
      { id: "su7", text: "Did support refuse to address your concerns?" },
      { id: "su8", text: "Were you given conflicting information by different agents?" },
      { id: "su9", text: "Did support claim they couldn't help with your issue?" },
      { id: "su10", text: "Were you unable to get a clear answer to your question?" },
      { id: "su11", text: "Did support disconnect or close your chat without resolution?" },
      { id: "su12", text: "Were you unable to contact support during business hours?" },
      { id: "su13", text: "Did support provide no timeline for resolution?" },
      { id: "su14", text: "Were you transferred between agents multiple times?" },
      { id: "su15", text: "Did support refuse to document your issue?" },
      { id: "su16", text: "Were you unable to follow up on your ticket?" },
      { id: "su17", text: "Did support claim your issue was 'not their responsibility'?" },
      { id: "su18", text: "Were you unable to get support in your language?" },
      { id: "su19", text: "Did support offer no compensation for the poor service?" },
      { id: "su20", text: "Were you unable to file a formal complaint?" },
      { id: "su21", text: "Did support refuse to provide a ticket number?" },
      { id: "su22", text: "Were you told to contact support via a different channel?" },
      { id: "su23", text: "Did support provide false information?" },
      { id: "su24", text: "Were you unable to get a response to follow-up messages?" },
      { id: "su25", text: "Did support close your ticket without resolution?" },
      { id: "su26", text: "Were you unable to speak with a human agent?" },
      { id: "su27", text: "Did support refuse to acknowledge your issue?" },
      { id: "su28", text: "Were you given a different response each time you contacted support?" },
      { id: "su29", text: "Did support claim your issue was 'already resolved'?" },
      { id: "su30", text: "Were you unable to get support for urgent issues?" },
      { id: "su31", text: "Did support provide no solution to your problem?" },
      { id: "su32", text: "Were you told to 'wait' without any timeline?" },
      { id: "su33", text: "Did support refuse to investigate your complaint?" },
      { id: "su34", text: "Were you unable to reach support by phone?" },
      { id: "su35", text: "Did support provide unhelpful suggestions?" },
    ],
  },

  {
    id: "support_rude",
    name: "Support Rude/Unprofessional",
    description: "Support staff behaves unprofessionally or dismissively",
    riskWeight: 6,
    questions: [
      { id: "sr1", text: "Was support staff rude or dismissive?" },
      { id: "sr2", text: "Did support use unprofessional language?" },
      { id: "sr3", text: "Were you treated disrespectfully?" },
      { id: "sr4", text: "Did support mock or belittle your concerns?" },
      { id: "sr5", text: "Were you blamed for the casino's mistakes?" },
      { id: "sr6", text: "Did support refuse to apologize for errors?" },
      { id: "sr7", text: "Were you threatened by support staff?" },
      { id: "sr8", text: "Did support use aggressive language?" },
      { id: "sr9", text: "Were you made to feel unwelcome?" },
      { id: "sr10", text: "Did support refuse to listen to your concerns?" },
      { id: "sr11", text: "Were you interrupted or cut off?" },
      { id: "sr12", text: "Did support make personal attacks?" },
      { id: "sr13", text: "Were you accused of being dishonest?" },
      { id: "sr14", text: "Did support refuse to take you seriously?" },
      { id: "sr15", text: "Were you made to feel like a burden?" },
      { id: "sr16", text: "Did support use sarcasm or condescension?" },
      { id: "sr17", text: "Were you denied basic respect?" },
      { id: "sr18", text: "Did support refuse to help despite your valid concerns?" },
      { id: "sr19", text: "Were you treated differently than other players?" },
      { id: "sr20", text: "Did support make you feel discriminated against?" },
      { id: "sr21", text: "Were you pressured to accept an unfair settlement?" },
      { id: "sr22", text: "Did support refuse to acknowledge your frustration?" },
      { id: "sr23", text: "Were you told your concerns were 'invalid'?" },
      { id: "sr24", text: "Did support refuse to provide a supervisor?" },
      { id: "sr25", text: "Were you hung up on or disconnected intentionally?" },
      { id: "sr26", text: "Did support make promises they didn't keep?" },
      { id: "sr27", text: "Were you made to feel like you were overreacting?" },
      { id: "sr28", text: "Did support refuse to acknowledge their mistakes?" },
      { id: "sr29", text: "Were you told to 'deal with it'?" },
      { id: "sr30", text: "Did support refuse to escalate your complaint?" },
      { id: "sr31", text: "Were you treated as if you were lying?" },
      { id: "sr32", text: "Did support refuse to provide compensation for poor service?" },
      { id: "sr33", text: "Were you made to feel ashamed for complaining?" },
      { id: "sr34", text: "Did support refuse to take responsibility?" },
      { id: "sr35", text: "Were you treated unprofessionally in writing?" },
    ],
  },

  {
    id: "technical_glitches",
    name: "Technical Glitches",
    description: "Website crashes, freezes, or loses session data",
    riskWeight: 6,
    questions: [
      { id: "tg1", text: "Did the website crash during your session?" },
      { id: "tg2", text: "Were you logged out unexpectedly?" },
      { id: "tg3", text: "Did the website freeze or become unresponsive?" },
      { id: "tg4", text: "Were your bets lost during a technical glitch?" },
      { id: "tg5", text: "Did the casino refuse to honor lost bets?" },
      { id: "tg6", text: "Were you unable to access your account?" },
      { id: "tg7", text: "Did the website display incorrect balance information?" },
      { id: "tg8", text: "Were transactions not recorded properly?" },
      { id: "tg9", text: "Did the casino claim technical issues were 'not their fault'?" },
      { id: "tg10", text: "Were you unable to contact support about technical issues?" },
      { id: "tg11", text: "Did the casino offer no compensation for technical problems?" },
      { id: "tg12", text: "Were technical issues recurring?" },
      { id: "tg13", text: "Did the website load very slowly?" },
      { id: "tg14", text: "Were you unable to place bets during technical issues?" },
      { id: "tg15", text: "Did the casino refuse to investigate technical problems?" },
      { id: "tg16", text: "Were you unable to withdraw during technical issues?" },
      { id: "tg17", text: "Did the casino claim technical issues were 'temporary'?" },
      { id: "tg18", text: "Were you unable to access live chat during issues?" },
      { id: "tg19", text: "Did the website display error messages without explanation?" },
      { id: "tg20", text: "Were you unable to complete transactions?" },
      { id: "tg21", text: "Did the casino lose your session data?" },
      { id: "tg22", text: "Were you charged for failed transactions?" },
      { id: "tg23", text: "Did the casino refuse to refund failed transactions?" },
      { id: "tg24", text: "Were you unable to use the website on mobile?" },
      { id: "tg25", text: "Did the website have compatibility issues?" },
      { id: "tg26", text: "Were you unable to navigate the website?" },
      { id: "tg27", text: "Did the casino refuse to fix recurring technical issues?" },
      { id: "tg28", text: "Were you unable to access your account history?" },
      { id: "tg29", text: "Did the casino blame technical issues on your device?" },
      { id: "tg30", text: "Were you unable to file a complaint about technical issues?" },
      { id: "tg31", text: "Did the casino provide no estimated time for fixes?" },
      { id: "tg32", text: "Were you unable to access customer support during outages?" },
      { id: "tg33", text: "Did the casino refuse to provide compensation for downtime?" },
      { id: "tg34", text: "Were technical issues affecting your ability to play?" },
      { id: "tg35", text: "Did the casino claim technical issues were 'beyond their control'?" },
    ],
  },

  // SECURITY & FRAUD ISSUES (11-15)
  {
    id: "data_breach",
    name: "Data Breach/Privacy Violation",
    description: "Personal information leaked or compromised",
    riskWeight: 10,
    questions: [
      { id: "db1", text: "Did the casino experience a data breach?" },
      { id: "db2", text: "Were you notified of the breach?" },
      { id: "db3", text: "Was your personal information compromised?" },
      { id: "db4", text: "Did the casino delay notifying you of the breach?" },
      { id: "db5", text: "Were your payment details exposed?" },
      { id: "db6", text: "Did the casino refuse to provide details about the breach?" },
      { id: "db7", text: "Were you offered no compensation for the breach?" },
      { id: "db8", text: "Did the casino refuse to investigate the breach?" },
      { id: "db9", text: "Were you unable to contact support about the breach?" },
      { id: "db10", text: "Did the casino claim the breach was 'not serious'?" },
      { id: "db11", text: "Were you unable to change your password after the breach?" },
      { id: "db12", text: "Did the casino refuse to provide breach details?" },
      { id: "db13", text: "Were you offered no identity protection services?" },
      { id: "db14", text: "Did the casino refuse to acknowledge the breach?" },
      { id: "db15", text: "Were you unable to file a complaint about the breach?" },
      { id: "db16", text: "Did the casino claim the breach was 'beyond their control'?" },
      { id: "db17", text: "Were you offered no financial compensation?" },
      { id: "db18", text: "Did the casino refuse to implement better security?" },
      { id: "db19", text: "Were your documents or ID photos exposed?" },
      { id: "db20", text: "Did the casino refuse to provide a security report?" },
      { id: "db21", text: "Were you unable to verify the breach was fixed?" },
      { id: "db22", text: "Did the casino claim the breach was 'isolated'?" },
      { id: "db23", text: "Were you offered no credit monitoring?" },
      { id: "db24", text: "Did the casino refuse to notify other affected users?" },
      { id: "db25", text: "Were you unable to get details about what was exposed?" },
      { id: "db26", text: "Did the casino refuse to cooperate with authorities?" },
      { id: "db27", text: "Were you offered no legal support?" },
      { id: "db28", text: "Did the casino claim the breach was 'not their fault'?" },
      { id: "db29", text: "Were you unable to receive updates on the breach?" },
      { id: "db30", text: "Did the casino refuse to provide a timeline for fixes?" },
      { id: "db31", text: "Were you offered no settlement for the breach?" },
      { id: "db32", text: "Did the casino refuse to acknowledge your concerns?" },
      { id: "db33", text: "Were you unable to verify your account security?" },
      { id: "db34", text: "Did the casino refuse to implement two-factor authentication?" },
      { id: "db35", text: "Were you offered no alternative account protection?" },
    ],
  },

  {
    id: "account_hacked",
    name: "Account Hacked",
    description: "Unauthorized access or fraudulent activity on account",
    riskWeight: 9,
    questions: [
      { id: "ah1", text: "Was your account hacked or accessed without permission?" },
      { id: "ah2", text: "Did you notice unauthorized transactions?" },
      { id: "ah3", text: "Was your balance reduced without your action?" },
      { id: "ah4", text: "Did the casino refuse to investigate the hack?" },
      { id: "ah5", text: "Were you unable to regain access to your account?" },
      { id: "ah6", text: "Did the casino refuse to refund fraudulent transactions?" },
      { id: "ah7", text: "Were you unable to change your password?" },
      { id: "ah8", text: "Did the casino claim you were responsible for the hack?" },
      { id: "ah9", text: "Were you offered no compensation for the hack?" },
      { id: "ah10", text: "Did the casino refuse to provide security details?" },
      { id: "ah11", text: "Were you unable to contact support about the hack?" },
      { id: "ah12", text: "Did the casino refuse to implement better security?" },
      { id: "ah13", text: "Were you unable to verify the hack was fixed?" },
      { id: "ah14", text: "Did the casino claim the hack was 'not serious'?" },
      { id: "ah15", text: "Were you offered no identity protection?" },
      { id: "ah16", text: "Did the casino refuse to acknowledge the hack?" },
      { id: "ah17", text: "Were you unable to file a complaint about the hack?" },
      { id: "ah18", text: "Did the casino claim the hack was 'beyond their control'?" },
      { id: "ah19", text: "Were you offered no financial compensation?" },
      { id: "ah20", text: "Did the casino refuse to provide a security report?" },
      { id: "ah21", text: "Were you unable to recover your account?" },
      { id: "ah22", text: "Did the casino claim you were negligent?" },
      { id: "ah23", text: "Were you offered no alternative account protection?" },
      { id: "ah24", text: "Did the casino refuse to implement two-factor authentication?" },
      { id: "ah25", text: "Were you unable to get details about the hack?" },
      { id: "ah26", text: "Did the casino refuse to cooperate with authorities?" },
      { id: "ah27", text: "Were you offered no legal support?" },
      { id: "ah28", text: "Did the casino claim the hack was 'your fault'?" },
      { id: "ah29", text: "Were you unable to receive updates on the hack?" },
      { id: "ah30", text: "Did the casino refuse to provide a timeline for fixes?" },
      { id: "ah31", text: "Were you offered no settlement for the hack?" },
      { id: "ah32", text: "Did the casino refuse to acknowledge your concerns?" },
      { id: "ah33", text: "Were you unable to verify your account security?" },
      { id: "ah34", text: "Did the casino refuse to provide security logs?" },
      { id: "ah35", text: "Were you offered no credit monitoring?" },
    ],
  },

  {
    id: "false_advertising",
    name: "False/Misleading Advertising",
    description: "Casino advertises false promotions or misleading offers",
    riskWeight: 6,
    questions: [
      { id: "fa1", text: "Did the casino advertise false promotions?" },
      { id: "fa2", text: "Were bonus terms different than advertised?" },
      { id: "fa3", text: "Did the casino claim bonuses that didn't exist?" },
      { id: "fa4", text: "Were you unable to claim advertised bonuses?" },
      { id: "fa5", text: "Did the casino change bonus terms after advertising?" },
      { id: "fa6", text: "Were bonus conditions hidden or unclear?" },
      { id: "fa7", text: "Did the casino advertise unrealistic odds?" },
      { id: "fa8", text: "Were you misled about game fairness?" },
      { id: "fa9", text: "Did the casino advertise false licensing?" },
      { id: "fa10", text: "Were you misled about payment options?" },
      { id: "fa11", text: "Did the casino advertise false withdrawal speeds?" },
      { id: "fa12", text: "Were you misled about customer support availability?" },
      { id: "fa13", text: "Did the casino advertise false security features?" },
      { id: "fa14", text: "Were you misled about responsible gambling tools?" },
      { id: "fa15", text: "Did the casino advertise false player protections?" },
      { id: "fa16", text: "Were you misled about game selection?" },
      { id: "fa17", text: "Did the casino advertise false welcome bonuses?" },
      { id: "fa18", text: "Were you misled about loyalty programs?" },
      { id: "fa19", text: "Did the casino advertise false VIP benefits?" },
      { id: "fa20", text: "Were you misled about deposit methods?" },
      { id: "fa21", text: "Did the casino advertise false return rates?" },
      { id: "fa22", text: "Were you misled about player testimonials?" },
      { id: "fa23", text: "Did the casino use fake reviews?" },
      { id: "fa24", text: "Were you misled by celebrity endorsements?" },
      { id: "fa25", text: "Did the casino advertise false regulatory approval?" },
      { id: "fa26", text: "Were you unable to verify advertised claims?" },
      { id: "fa27", text: "Did the casino refuse to honor advertised offers?" },
      { id: "fa28", text: "Were you offered no compensation for false advertising?" },
      { id: "fa29", text: "Did the casino refuse to acknowledge false advertising?" },
      { id: "fa30", text: "Were you unable to file a complaint about false advertising?" },
      { id: "fa31", text: "Did the casino claim false advertising was 'not intentional'?" },
      { id: "fa32", text: "Were you misled about bonus expiration?" },
      { id: "fa33", text: "Did the casino advertise false tournament prizes?" },
      { id: "fa34", text: "Were you misled about cashback offers?" },
      { id: "fa35", text: "Did the casino advertise false referral bonuses?" },
    ],
  },

  {
    id: "unlicensed_operation",
    name: "Unlicensed Operation",
    description: "Casino operates without proper license or regulation",
    riskWeight: 10,
    questions: [
      { id: "ul1", text: "Is the casino unlicensed or unregulated?" },
      { id: "ul2", text: "Did the casino claim to be licensed without proof?" },
      { id: "ul3", text: "Were you unable to verify the casino's license?" },
      { id: "ul4", text: "Did the casino refuse to provide license information?" },
      { id: "ul5", text: "Was the casino's license expired?" },
      { id: "ul6", text: "Did the casino operate in a jurisdiction where it's illegal?" },
      { id: "ul7", text: "Were you unable to find the casino in regulatory databases?" },
      { id: "ul8", text: "Did the casino refuse to comply with regulations?" },
      { id: "ul9", text: "Were you offered no player protections?" },
      { id: "ul10", text: "Did the casino refuse to implement responsible gambling tools?" },
      { id: "ul11", text: "Were you unable to file complaints with regulators?" },
      { id: "ul12", text: "Did the casino refuse to undergo audits?" },
      { id: "ul13", text: "Were you offered no recourse for disputes?" },
      { id: "ul14", text: "Did the casino refuse to segregate player funds?" },
      { id: "ul15", text: "Were you unable to verify game fairness?" },
      { id: "ul16", text: "Did the casino refuse to provide RNG certification?" },
      { id: "ul17", text: "Were you offered no KYC verification?" },
      { id: "ul18", text: "Did the casino refuse to implement AML compliance?" },
      { id: "ul19", text: "Were you offered no data protection?" },
      { id: "ul20", text: "Did the casino refuse to provide terms and conditions?" },
      { id: "ul21", text: "Were you unable to verify the casino's ownership?" },
      { id: "ul22", text: "Did the casino refuse to provide contact information?" },
      { id: "ul23", text: "Were you offered no dispute resolution?" },
      { id: "ul24", text: "Did the casino refuse to comply with player requests?" },
      { id: "ul25", text: "Were you offered no responsible gambling support?" },
      { id: "ul26", text: "Did the casino refuse to honor player agreements?" },
      { id: "ul27", text: "Were you offered no compensation for losses?" },
      { id: "ul28", text: "Did the casino refuse to acknowledge complaints?" },
      { id: "ul29", text: "Were you unable to contact regulators about the casino?" },
      { id: "ul30", text: "Did the casino refuse to provide financial information?" },
      { id: "ul31", text: "Were you offered no player fund protection?" },
      { id: "ul32", text: "Did the casino refuse to implement security measures?" },
      { id: "ul33", text: "Were you offered no dispute mediation?" },
      { id: "ul34", text: "Did the casino refuse to provide transparency?" },
      { id: "ul35", text: "Were you unable to verify the casino's legitimacy?" },
    ],
  },

  // TERMS & CONDITIONS ISSUES (16-20)
  {
    id: "terms_changed",
    name: "Terms Changed Without Notice",
    description: "Casino unilaterally changed terms affecting players",
    riskWeight: 7,
    questions: [
      { id: "tc1", text: "Did the casino change terms without notice?" },
      { id: "tc2", text: "Were the new terms unfavorable to players?" },
      { id: "tc3", text: "Did the casino claim changes were 'necessary'?" },
      { id: "tc4", text: "Were you unable to opt-out of new terms?" },
      { id: "tc5", text: "Did the casino change withdrawal terms?" },
      { id: "tc6", text: "Were bonus terms changed after you accepted them?" },
      { id: "tc7", text: "Did the casino change deposit limits?" },
      { id: "tc8", text: "Were responsible gambling terms changed?" },
      { id: "tc9", text: "Did the casino change account closure terms?" },
      { id: "tc10", text: "Were fee terms changed?" },
      { id: "tc11", text: "Did the casino change game availability?" },
      { id: "tc12", text: "Were payment method terms changed?" },
      { id: "tc13", text: "Did the casino change verification requirements?" },
      { id: "tc14", text: "Were dispute resolution terms changed?" },
      { id: "tc15", text: "Did the casino change privacy terms?" },
      { id: "tc16", text: "Were you unable to access old terms?" },
      { id: "tc17", text: "Did the casino refuse to explain the changes?" },
      { id: "tc18", text: "Were you offered no compensation for unfavorable changes?" },
      { id: "tc19", text: "Did the casino claim changes were 'for your protection'?" },
      { id: "tc20", text: "Were you unable to contact support about changes?" },
      { id: "tc21", text: "Did the casino refuse to revert unfavorable changes?" },
      { id: "tc22", text: "Were you unable to file a complaint about changes?" },
      { id: "tc23", text: "Did the casino apply changes retroactively?" },
      { id: "tc24", text: "Were you affected by changes you didn't agree to?" },
      { id: "tc25", text: "Did the casino claim changes were 'mandatory'?" },
      { id: "tc26", text: "Were you unable to understand the new terms?" },
      { id: "tc27", text: "Did the casino refuse to provide old terms?" },
      { id: "tc28", text: "Were changes announced in an unclear manner?" },
      { id: "tc29", text: "Did the casino change terms multiple times?" },
      { id: "tc30", text: "Were you unable to access your account due to changes?" },
      { id: "tc31", text: "Did the casino refuse to honor old terms?" },
      { id: "tc32", text: "Were you offered no transition period?" },
      { id: "tc33", text: "Did the casino change terms affecting your balance?" },
      { id: "tc34", text: "Were you unable to withdraw due to new terms?" },
      { id: "tc35", text: "Did the casino claim changes were 'non-negotiable'?" },
    ],
  },

  {
    id: "rg_tools_missing",
    name: "Responsible Gambling Tools Missing",
    description: "Deposit limits, self-exclusion, or other RG tools unavailable",
    riskWeight: 7,
    questions: [
      { id: "rg1", text: "Were deposit limits unavailable?" },
      { id: "rg2", text: "Did the casino refuse to set deposit limits?" },
      { id: "rg3", text: "Were self-exclusion options unavailable?" },
      { id: "rg4", text: "Did the casino refuse to allow self-exclusion?" },
      { id: "rg5", text: "Were loss limits unavailable?" },
      { id: "rg6", text: "Did the casino refuse to set loss limits?" },
      { id: "rg7", text: "Were time-out features unavailable?" },
      { id: "rg8", text: "Did the casino refuse to implement time-outs?" },
      { id: "rg9", text: "Were reality check reminders unavailable?" },
      { id: "rg10", text: "Did the casino refuse to provide reality checks?" },
      { id: "rg11", text: "Were problem gambling resources unavailable?" },
      { id: "rg12", text: "Did the casino refuse to provide support resources?" },
      { id: "rg13", text: "Were age verification tools unavailable?" },
      { id: "rg14", text: "Did the casino refuse to verify age?" },
      { id: "rg15", text: "Were cooling-off periods unavailable?" },
      { id: "rg16", text: "Did the casino refuse to offer cooling-off periods?" },
      { id: "rg17", text: "Were gambling history tools unavailable?" },
      { id: "rg18", text: "Did the casino refuse to provide gambling history?" },
      { id: "rg19", text: "Were spending limits unavailable?" },
      { id: "rg20", text: "Did the casino refuse to set spending limits?" },
      { id: "rg21", text: "Were betting limits unavailable?" },
      { id: "rg22", text: "Did the casino refuse to set betting limits?" },
      { id: "rg23", text: "Were session duration limits unavailable?" },
      { id: "rg24", text: "Did the casino refuse to set session limits?" },
      { id: "rg25", text: "Were problem gambling links unavailable?" },
      { id: "rg26", text: "Did the casino refuse to provide help links?" },
      { id: "rg27", text: "Were RG tools difficult to find?" },
      { id: "rg28", text: "Did the casino hide RG tools?" },
      { id: "rg29", text: "Were RG tools not working properly?" },
      { id: "rg30", text: "Did the casino refuse to fix broken RG tools?" },
      { id: "rg31", text: "Were RG tools not accessible on mobile?" },
      { id: "rg32", text: "Did the casino refuse to provide mobile RG tools?" },
      { id: "rg33", text: "Were RG tools available only after registration?" },
      { id: "rg34", text: "Did the casino refuse to provide pre-registration RG info?" },
      { id: "rg35", text: "Were RG tools not available in your language?" },
    ],
  },

  {
    id: "rg_tools_ignored",
    name: "Responsible Gambling Tools Ignored",
    description: "Set limits but casino ignored them",
    riskWeight: 8,
    questions: [
      { id: "rgi1", text: "Did the casino ignore your deposit limit?" },
      { id: "rgi2", text: "Were you able to deposit beyond your limit?" },
      { id: "rgi3", text: "Did the casino ignore your loss limit?" },
      { id: "rgi4", text: "Were you able to lose beyond your limit?" },
      { id: "rgi5", text: "Did the casino ignore your self-exclusion?" },
      { id: "rgi6", text: "Were you able to access your account after self-exclusion?" },
      { id: "rgi7", text: "Did the casino ignore your time-out?" },
      { id: "rgi8", text: "Were you able to play during your time-out?" },
      { id: "rgi9", text: "Did the casino ignore your spending limit?" },
      { id: "rgi10", text: "Were you able to spend beyond your limit?" },
      { id: "rgi11", text: "Did the casino ignore your betting limit?" },
      { id: "rgi12", text: "Were you able to bet beyond your limit?" },
      { id: "rgi13", text: "Did the casino ignore your session limit?" },
      { id: "rgi14", text: "Were you able to play beyond your session limit?" },
      { id: "rgi15", text: "Did the casino ignore your cooling-off period?" },
      { id: "rgi16", text: "Were you able to access your account during cooling-off?" },
      { id: "rgi17", text: "Did the casino send promotional emails despite your request?" },
      { id: "rgi18", text: "Were you contacted by support to encourage deposits?" },
      { id: "rgi19", text: "Did the casino offer bonuses despite your limits?" },
      { id: "rgi20", text: "Were you encouraged to increase your limits?" },
      { id: "rgi21", text: "Did the casino reset your limits without permission?" },
      { id: "rgi22", text: "Were your limits removed without notice?" },
      { id: "rgi23", text: "Did the casino claim limits were 'not enforceable'?" },
      { id: "rgi24", text: "Were you unable to verify your limits were set?" },
      { id: "rgi25", text: "Did the casino refuse to honor your limits?" },
      { id: "rgi26", text: "Were you offered no compensation for ignored limits?" },
      { id: "rgi27", text: "Did the casino refuse to acknowledge ignored limits?" },
      { id: "rgi28", text: "Were you unable to contact support about ignored limits?" },
      { id: "rgi29", text: "Did the casino refuse to investigate ignored limits?" },
      { id: "rgi30", text: "Were you unable to file a complaint about ignored limits?" },
      { id: "rgi31", text: "Did the casino claim ignored limits were 'your fault'?" },
      { id: "rgi32", text: "Were you offered no refund for losses beyond your limit?" },
      { id: "rgi33", text: "Did the casino refuse to provide evidence of limits?" },
      { id: "rgi34", text: "Were you unable to verify limits were enforced?" },
      { id: "rgi35", text: "Did the casino claim limits were 'overridden' by system?" },
    ],
  },

  {
    id: "suspected_fraud",
    name: "Suspected Fraud",
    description: "Strong suspicion that casino is running a scam",
    riskWeight: 10,
    questions: [
      { id: "sf1", text: "Do you suspect the casino is fraudulent?" },
      { id: "sf2", text: "Has the casino engaged in deceptive practices?" },
      { id: "sf3", text: "Do you suspect the casino is stealing from players?" },
      { id: "sf4", text: "Has the casino refused to pay legitimate winnings?" },
      { id: "sf5", text: "Do you suspect the casino is manipulating games?" },
      { id: "sf6", text: "Has the casino engaged in money laundering?" },
      { id: "sf7", text: "Do you suspect the casino is a Ponzi scheme?" },
      { id: "sf8", text: "Has the casino promised unrealistic returns?" },
      { id: "sf9", text: "Do you suspect the casino is using fake credentials?" },
      { id: "sf10", text: "Has the casino engaged in identity theft?" },
      { id: "sf11", text: "Do you suspect the casino is operating illegally?" },
      { id: "sf12", text: "Has the casino refused to comply with regulations?" },
      { id: "sf13", text: "Do you suspect the casino is connected to organized crime?" },
      { id: "sf14", text: "Has the casino engaged in market manipulation?" },
      { id: "sf15", text: "Do you suspect the casino is using player funds illegally?" },
      { id: "sf16", text: "Has the casino engaged in tax evasion?" },
      { id: "sf17", text: "Do you suspect the casino is funding illegal activities?" },
      { id: "sf18", text: "Has the casino engaged in bribery or corruption?" },
      { id: "sf19", text: "Do you suspect the casino is exploiting vulnerable players?" },
      { id: "sf20", text: "Has the casino engaged in predatory lending?" },
      { id: "sf21", text: "Do you suspect the casino is running a scam?" },
      { id: "sf22", text: "Has the casino engaged in false advertising?" },
      { id: "sf23", text: "Do you suspect the casino is using fake reviews?" },
      { id: "sf24", text: "Has the casino engaged in phishing or hacking?" },
      { id: "sf25", text: "Do you suspect the casino is stealing personal data?" },
      { id: "sf26", text: "Has the casino engaged in account takeover?" },
      { id: "sf27", text: "Do you suspect the casino is running a Botnet?" },
      { id: "sf28", text: "Has the casino engaged in ransomware attacks?" },
      { id: "sf29", text: "Do you suspect the casino is involved in trafficking?" },
      { id: "sf30", text: "Has the casino engaged in extortion?" },
      { id: "sf31", text: "Do you suspect the casino is running a pyramid scheme?" },
      { id: "sf32", text: "Has the casino engaged in embezzlement?" },
      { id: "sf33", text: "Do you suspect the casino is using shell companies?" },
      { id: "sf34", text: "Has the casino engaged in market fraud?" },
      { id: "sf35", text: "Do you suspect the casino is connected to criminal networks?" },
    ],
  },
];

export const REGULATORY_STANDARDS = [
  {
    code: "4.10",
    title: "Responsible Gambling Tools",
    description: "Operators must provide deposit limits, self-exclusion, loss limits, and time-out features",
    category: "Responsible Gambling",
    provincialDueProcess: "Players must be able to set limits within 24 hours; limits take effect immediately or next login",
  },
  {
    code: "5.01",
    title: "Player Account Security",
    description: "Operators must implement multi-factor authentication and secure password policies",
    category: "Security",
    provincialDueProcess: "Accounts must be protected with MFA; password reset must be verified via email",
  },
  {
    code: "2.01",
    title: "Game Integrity & RNG Certification",
    description: "All games must use certified Random Number Generators audited annually",
    category: "Game Integrity",
    provincialDueProcess: "RNG certification must be renewed annually; audit reports must be available to AGCO",
  },
  {
    code: "3.01",
    title: "KYC & AML Compliance",
    description: "Know Your Customer verification required; Anti-Money Laundering monitoring mandatory",
    category: "Compliance",
    provincialDueProcess: "KYC must be completed within 7 days; AML screening must be done for all transactions over $10,000",
  },
  {
    code: "6.01",
    title: "Withdrawal Processing",
    description: "All withdrawals must be processed within 5 business days",
    category: "Payments",
    provincialDueProcess: "Operators must provide status updates; delays must be explained to players",
  },
  {
    code: "7.01",
    title: "Data Protection & Privacy",
    description: "Player data must be encrypted and protected; GDPR/PIPEDA compliance required",
    category: "Privacy",
    provincialDueProcess: "Data breaches must be reported to AGCO within 24 hours; players must be notified within 30 days",
  },
];

export const TRUTHS_AND_MYTHS = [
  {
    myth: "Online casinos always rig games to make you lose",
    truth: "Regulated casinos use certified RNGs audited regularly. Rigging is illegal and results in license revocation.",
    source: "AGCO Registrar Standards",
    category: "Game Integrity",
  },
  {
    myth: "Casinos steal deposits and claim they never received them",
    truth: "Regulated casinos must account for all funds. Theft is a criminal offense and investigated immediately.",
    source: "AGCO Regulations",
    category: "Payments",
  },
  {
    myth: "You can never withdraw money from online casinos",
    truth: "Regulated casinos must process withdrawals within 5-7 business days. Persistent denial is a red flag.",
    source: "AGCO Standards",
    category: "Payments",
  },
  {
    myth: "Bonuses are just tricks to take your money",
    truth: "Bonuses are real but have legitimate wagering requirements (typically 20-40x). Read terms carefully.",
    source: "Industry Best Practices",
    category: "Promotions",
  },
  {
    myth: "KYC verification is a scam to avoid paying winners",
    truth: "KYC is legal compliance required by all regulated casinos. It protects against fraud and money laundering.",
    source: "FINTRAC Guidelines",
    category: "Compliance",
  },
  {
    myth: "Casinos lock accounts to steal your winnings",
    truth: "Accounts are locked for violations of terms. Legitimate reasons must be explained by the casino.",
    source: "AGCO Standards",
    category: "Account Management",
  },
  {
    myth: "Regulated casinos are more expensive than offshore",
    truth: "Regulated casinos have lower fraud risk, better payouts, and player protections. Offshore casinos offer no recourse.",
    source: "Industry Analysis",
    category: "Licensing",
  },
  {
    myth: "Customer support is always useless",
    truth: "Regulated casinos have professional support with response SLAs (typically 24-48 hours).",
    source: "AGCO Standards",
    category: "Support",
  },
  {
    myth: "You will always lose money at online casinos",
    truth: "Regulated casinos have verified RTPs of 95-98%. You can win, but the house has a mathematical edge.",
    source: "Game Certification",
    category: "Game Integrity",
  },
  {
    myth: "Offshore casinos are the same as regulated ones",
    truth: "Offshore casinos have no player protections, no recourse for disputes, and no regulatory oversight.",
    source: "Player Protection Organizations",
    category: "Licensing",
  },
];
